### ISSUE TITLE
Draconic Evolution Portal Crash

### ISSUE THREAD

**Issue by pikerdj** [FTBTeam/FTB-Academy#225]
Time: 2019-12-01 12:10:06 EST
Description: Ticking block entity

java.lang.NullPointerException
    at com.brandon3055.draconicevolution.handlers.DislocatorLinkHandler.getAndValidatePlayerPos(DislocatorLinkHandler.java:177)
    at com.brandon3055.draconicevolution.handlers.DislocatorLinkHandler.getLinkPos(DislocatorLinkHandler.java:113)
    at com.brandon3055.draconicevolution.items.tools.DislocatorBound.getLocation(DislocatorBound.java:220)
    at com.brandon3055.draconicevolution.blocks.tileentity.TileDislocatorReceptacle.update(TileDislocatorReceptacle.java:123)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zzj000(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by pikerdj** [comment]
Happened again, same issue with the DE dislocator.
https://pastebin.com/PXB8EGdR
