### ISSUE TITLE
Forge crash on server start.sh script

### ISSUE THREAD

**Issue by oytunistrator** [FTBTeam/FTB-Academy#348]
* **Modpack Version**: 
FTB Academy - 1.4.0 (Server Files Only)

* **Issue**: 
Forge Crash on Server Launch. Installed with serverinstall_1_158 script.  And also same with start.bat on Windows 10.

Files downloaded from [https://www.feed-the-beast.com/modpack/ftb_academy](https://www.feed-the-beast.com/modpack/ftb_academy). Clicked Mac Version and run serverinstall_1_158. Installed all files success.

* **Java Version**:
```
java -version
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing
```

* **Link to Log or Crash File Paste**: 

script.sh start log;
```
sh start.sh
Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?
[y/n] y
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

```

installer.log:
```
java.net.preferIPv4Stack=true
Installing server to current directory
MESSAGE: Data kindly mirrored by Forge at http://MinecraftForge.net/
MESSAGE: Considering library net.minecraftforge:forge:1.12.2-14.23.5.2847: Not Downloading {Wrong Side}
MESSAGE: Considering library net.minecraft:launchwrapper:1.12
MESSAGE: Considering library org.ow2.asm:asm-all:5.2
MESSAGE: Considering library org.jline:jline:3.5.1
MESSAGE: Considering library net.java.dev.jna:jna:4.4.0
MESSAGE: Considering library com.typesafe.akka:akka-actor_2.11:2.3.3
MESSAGE: Considering library com.typesafe:config:1.2.1
MESSAGE: Considering library org.scala-lang:scala-actors-migration_2.11:1.1.0
MESSAGE: Considering library org.scala-lang:scala-compiler:2.11.1
MESSAGE: Considering library org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2
MESSAGE: Considering library org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2
MESSAGE: Considering library org.scala-lang:scala-library:2.11.1
MESSAGE: Considering library org.scala-lang:scala-parser-combinators_2.11:1.0.1
MESSAGE: Considering library org.scala-lang:scala-reflect:2.11.1
MESSAGE: Considering library org.scala-lang:scala-swing_2.11:1.0.1
MESSAGE: Considering library org.scala-lang:scala-xml_2.11:1.0.2
MESSAGE: Considering library lzma:lzma:0.0.1
MESSAGE: Considering library net.sf.jopt-simple:jopt-simple:5.0.3
MESSAGE: Considering library java3d:vecmath:1.5.2
MESSAGE: Considering library net.sf.trove4j:trove4j:3.0.3
MESSAGE: Considering library org.apache.maven:maven-artifact:3.5.3
Extracting: /forge-1.12.2-14.23.5.2847-universal.jar
To:          forge-1.12.2-14.23.5.2847-universal.jar
The server installed successfully, you should now be able to run the file forge-1.12.2-14.23.5.2847-universal.jar
You can delete this installer file now if you wish

```

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
No

* **Known Fix**:

**Comment by urmet** [comment]
Your java is 7 versions too new. get java 8 for running minecraft.

**Comment by oytunistrator** [comment]
Fix:
---

change start.sh file for fix;

```
#!/bin/bash
echo "Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?"
EULA=`read  -n 1 -p "[y/n] "`
if [ "$EULA" = "y" ]; then
    echo "eula=true" > eula.txt
fi
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/
java -server -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx4096M -Xms3072M -jar forge-1.12.2-14.23.5.2847-universal.jar nogui
```

JAVA_HOME not found in environment.

**Comment by oytunistrator** [comment]
Server started but diffrent errors:
[latest.log](https://github.com/FTBTeam/FTB-Academy/files/5484253/latest.log)
