### ISSUE TITLE
[bug] There cannot be more than two players on a server aternos.org with FTB Academy modpack 1.16

### ISSUE THREAD

**Issue by Koutawars** [FTBTeam/FTB-Academy#377]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
![image](https://user-images.githubusercontent.com/24954437/131932403-a0cd2bc5-feee-4d55-a9cc-223cfabea963.png)
![image](https://user-images.githubusercontent.com/24954437/131932446-cf5332c0-3eb6-48a7-99f7-1c6bd37263e0.png)
![image](https://user-images.githubusercontent.com/24954437/131932471-7043fadd-3d3c-455e-9443-0392170e98fd.png)
![image](https://user-images.githubusercontent.com/24954437/131932492-0ba76735-8ae6-445b-8078-78291405d5c2.png)
![image](https://user-images.githubusercontent.com/24954437/131932520-210bb544-dfb0-40a4-9b8a-45a2927c9c9c.png)

**Forge / Fabric version, if applicable**
ForgeVersion: 36.1.4
JAVA: JDK 11.0.12.7 hotspot

**Modpack (with version), if applicable**
modpack: FTB Academy 1.16
modpack version: 1.1.0

**If the issue is a crash; An external link to the crash report**

**client crash**

02Sep2021 12:58:02.264] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 2574 advancements
[02Sep2021 12:58:09.416] [Render thread/INFO] [MobEffects/MOD]: Facade Accessor: team.chisel.ctm.api.IFacade
[02Sep2021 12:58:14.470] [Worker-Main-7/WARN] [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService/]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@3bc7556c[id=e99cdd10-378e-3df1-88e1-6420f01f553c,name=Carmig,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:125) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:99) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:179) ~[authlib-2.1.28.jar:?]
	at net.minecraft.client.resources.SkinManager.func_229293_a_(SourceFile:101) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:105) ~[authlib-2.1.28.jar:?]
	... 10 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:105) ~[authlib-2.1.28.jar:?]
	... 10 more

**Server log**

[02Sep2021 17:31:42.237] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: Koutaward[/186.82.86.208:48017] logged in with entity id 8256 at (-135.30000001192093, 83.0, -162.30000001192093)
1432 | [02Sep2021 17:31:42.263] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Koutaward joined the game
1433 | [02Sep2021 17:31:42.619] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Recipe packet size: 494911
1434 | [02Sep2021 17:31:42.619] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Item stack bytes: 121942
1435 | [02Sep2021 17:31:42.619] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: RL path bytes: 109604
1436 | [02Sep2021 17:31:42.619] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Ingredient cache size: 2424
1437 | [02Sep2021 17:31:42.620] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Ingredient cache hits: 29294
1438 | [02Sep2021 17:31:42.786] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Recipe packet size: 494912
1439 | [02Sep2021 17:31:42.786] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Item stack bytes: 121942
1440 | [02Sep2021 17:31:42.786] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: RL path bytes: 109604
1441 | [02Sep2021 17:31:42.786] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Ingredient cache size: 2424
1442 | [02Sep2021 17:31:42.787] [Netty Epoll Server IO #3/INFO] [recipebuffers - WRITE/]: Ingredient cache hits: 29294
1443 | [02Sep2021 17:31:46.639] [Server thread/ERROR] [com.lothrazar.cyclic.ModCyclic/]: Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
1444 | [02Sep2021 17:31:46.704] [Server thread/ERROR] [com.lothrazar.cyclic.ModCyclic/]: Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
1445 | [02Sep2021 17:32:02.992] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Koutaward lost connection: Timed out

**How to reproduce the issue**
when there is more than one connected, disconnect the second player who tries to enter .

*Please provide use with a step by step description*
- A player connects
- Another player is trying to connect
- The second player gets an error 

**A screenshot, if applicable**
![image](https://user-images.githubusercontent.com/24954437/131932662-9be0307e-a6b4-444b-8b1a-56ec24de2740.png)

**Anything else we should know?**
- The server is on the Athernos.org page with the modpack downloaded by the server itself. 
- The server don't crash, client only

**Comment by aaronhowser1** [comment]
This is the issue tracker for Academy 1.12, the 1.16 location is here: https://www.feed-the-beast.com/support

I haven't seen this problem though, and Aternos isn't known for it's *quality*. You get what you pay for, really. If you have access to access to the server files, try clearing out the mods, configs, defaultconfigs, and kubejs folder and replacing them with the ones in your client.
